config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  default_url_options host: "https://dogseekers.herokuapp.com"

  root to: 'homepages#index'

  get "dogs/adoption", as: "adoption_info"
  get "dogs/home", as: "dog_home_info"
  get "dogs/training", as: "training_info"
  get "dogs/problems", as: "problems_info"
  get "dogs/grooming", as: "grooming_info"
  get "dogs/videos", as: "videos"
  get "dogs/involvement", as: "get_involved"
  resources :dogs, only: [:index, :show]

  get "searchs/index"

  namespace :admin do
    resources :dogs, only: [:edit, :create, :update, :new]
  end

  namespace :admin do
    resources :admins, only: [:index, :show]
  end

  resources :breeds, only: [:index, :show]

  devise_scope :admin do
    get "admins/sign_out" => "devise/sessions#destroy"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validate :sanitize_email

  def filters
    bad_filter = LanguageFilter::Filter.new matchlist: :profanity
    sex_filter = LanguageFilter::Filter.new matchlist: :sex
  end

  def sanitize_email
    errors.add(:email, ": This kind of language is inappropriate.") if filters.match?(email)
  end

  has_many :dogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # include search filter in app record for global access
  include SearchFilter
end

app/models/breed.rb
class Breed < ApplicationRecord
end

app/models/concerns/search_filter.rb
module SearchFilter
  extend ActiveSupport::Concern

  module ClassMethods
    def search_filter(filter_params)
      results = self.where(nil)
      filter_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/dog.rb
require 'gravtastic'
class Dog < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include Gravtastic

  validate :sanitize_dog_name
  validate :sanitize_breed
  validate :sanitize_birth_date
  validate :sanitize_color
  validate :sanitize_photo

  def filters
    bad_filter = LanguageFilter::Filter.new matchlist: :profanity
    sex_filter = LanguageFilter::Filter.new matchlist: :sex
  end
  
  def sanitize_dog_name
    errors.add(:name, ": This kind of language is inappropriate.") if filters.match?(name)
  end

  def sanitize_breed
    errors.add(:breed, ": This kind of language is inappropriate.") if filters.match?(breed)
  end

  def sanitize_color
    errors.add(:color, ": This kind of language is inappropriate.") if filters.match?(color)
  end

  def sanitize_birth_date
    errors.add(:birth_date, ": This kind of language is inappropriate.") if filters.match?(birth_date)
  end

  def sanitize_photo
    errors.add(:photo, ": This kind of language is inappropriate.") if filters.match?(photo)
  end

  gravtastic :secure => true,
             :filetype => :jpg,
             :size => 250

  scope :location, -> (location) { where location: location }
  scope :breed, -> (breed) { where breed: breed }
  scope :title_age, -> (title_age) { where title_age: title_age }
  scope :gender, -> (gender) { where gender: gender }

  validates :name, presence: true
  validates :age, presence: true
  validates :title_age, presence: true
  validates :breed, presence: true
  validates :gender, presence: true
  validates :adoptable, presence: true
  validates :size, presence: true

  belongs_to :admin
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :admins
end

app/controllers/admin/dogs_controller.rb
class Admin::DogsController < ApplicationController
  before_action :set_dog, only: [:edit, :update]
  before_action :authenticate_admin!

  def new
    @dog = Dog.new
  end

  def create 
    @dog = Dog.new(dog_params)
    @dog.admin_id = current_admin.id
    if @dog.save
      AdminMailer.create_dog_email(current_admin).deliver_now
      flash[:success] = "Dog added successfully."
      redirect_to admin_admins_path
    else
      flash.now[:danger] = "Dog not added."
      render :new
    end
  end

  def edit
    if @dog.admin_id != current_admin.id
      flash[:danger] = "You can only edit the dog you posted"
      redirect_to admin_admins_path
    end
  end

  def update
    if @dog.admin_id != current_admin.id
      flash[:danger] = "You can only edit the dog you posted"
      redirect_to admin_admins_path
    else
      if @dog.update(dog_params)
        AdminMailer.update_dog_email(current_admin).deliver_now
        flash[:success] = "Dog successfully updated"
        redirect_to admin_admin_path(@dog)
      else
        flash.now[:danger] = "Dog unsuccessfully updated"
        render :edit
      end
    end
  end

  private

    def dog_params
      params.require(:dog)
        .permit(:name, :age, :breed, :gender, :adoptable,
                :color, :size, :photo, :location, :title_age, :birth_date)
    end

    def set_dog
      @dog = Dog.find(params[:id])
    end
end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]

  before_action :set_profile, only: [:edit, :update]

  def index
    @profiles = Profile.all
    @dogs = Dog.all
  end

  def show
    @dog = Dog.where(admin_id: params[:id])
  end

  def new
    @profile = Profile.new
  end

  def create 
    @profile = Profile.new(profile_params)
    if @profile.save
      flash[:success] = "Admin added successfully."
      redirect_to profile_admin_index
    else
      flash.now[:danger] = "Admin not added."
      render :new
    end
  end

  def edit
    if @profile.admin_id != current_admin.id
      flash[:danger] = "You can only edit the dog you posted"
      redirect_to profile_admin_index
    end
  end

  def update
    if @profile.admin_id != current_admin.id
      flash[:danger] = "You can only edit your own profile"
      redirect_to admin_dogs_path
    else
      if @profile.update(profile_params)
        flash[:success] = "Profile successfully updated"
        redirect_to profile_admin_index
      else
        flash.now[:danger] = "Profile unsuccessfully updated"
        render :edit
      end
    end
  end

  private

    def profile_params
      params.require(:admin)
        .permit(:email, :encrypted_password)
    end

    def set_profile
      @admin = Admin.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController

  def index
    @breeds = Breed.all
  end

  def show
    @breed = Breed.find(params[:id])
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
    @posted_by = Admin.find_by(id: @dog.admin_id)
  end

  def adoption
  end

  def home
  end

  def training
  end

  def problems
  end

  def grooming
  end

  def videos
  end

end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  protect_from_forgery with: :exception, prepend: true

  def index
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  
  def index
    @dogs = Dog.search_filter(params.slice(:location, :breed, :title_age, :gender))
  end

end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/dogs_helper.rb
module Admin::DogsHelper
  def is_admins_dog?
    current_admin.id == @dog.admin_id
  end
end

app/helpers/admin/profiles_helper.rb
module Admin::ProfilesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/admin/profiles/index.html.erb
<h1>Showing All Dogs</h1>
  <div class="doge-info">
    <% @dogs.each do |d| %>
      <h2 class="dog-name"><%= link_to d.name, admin_dog_path(d) %></h2>
      <div class="dog-photo">
        <%= image_tag d.photo, size: 250 %>
      </div>
      <h4 class="breed-name"><%= d.name %> is a <%= d.breed %></h4>
      <% if d.gender.titleize == "Female" %>
        <h4 class="dog-age">She is <%= d.age %> years old.</h4>
        <%= d.title_age.titleize %>
      <% else %>
        <h4 class="dog-age">He is <%= d.age %> years old.</h4>
        <%= d.title_age.titleize %>
      <% end %>
    <% end %>
  </div>
<h4><%= link_to "Home Page", root_path %></h4>
<h4><%= link_to "My Dogs", admin_profile_path(@profiles) %></h4>
<link rel="stylesheet" href="/css/custom.css">

app/views/admin/profiles/show.html.erb
<h1>Showing Dogs for <%= current_admin.email %></h1>
<h1>Meet <%= @dog.name %></h1>

<div class="doge-info">
  <div class="dog-photo">
    <%= image_tag @dog.photo, size: 250 %>
  </div>
  <h4 class="breed-name"><%= @dog.name %> is a <%= @dog.breed %></h4>
  <div class="dog-info-with-gender">
    <% if @dog.gender.titleize == "Female" %>
      <h4 class="dog-age">Title Age: <%= @dog.title_age.titleize %><br><br> Age: <%= @dog.age %></h4>
      <h4 class="dog-size-color">Dog Size: <%= @dog.size.titleize %><br><br> Color: <%= @dog.color.titleize %></h4>
      <h4 class="dog-birth">Birth Date <%= @dog.birth_date %></h4>
      <h4 class="dog-location">Location: <%= @dog.location %></h4>
    <% else %>
      <h4 class="dog-age">Title Age: <%= @dog.title_age.titleize %><br><br> Age: <%= @dog.age %></h4>
      <h4 class="dog-size-color">Size: <%= @dog.size.titleize %><br><br> Color: <%= @dog.color.titleize %></h4>
      <h4 class="dog-birth">Birth Date <%= @dog.birth_date %></h4>
      <h4 class="dog-location">Location: <%= @dog.location %></h4>
    <% end %>
  </div>
  <% if @dog.adoptable == true %>
    <h4>Available for adoption<h4>
  <% else %>
    <h4>Not available for adoption<h4>
  <% end %>
  <% if is_admins_dog? %>
    <%= link_to "Edit", [:edit, :admin, @dog]  %>
  <% end %>
</div>
<h4><%= link_to "Home Page", root_path %></h4>
<link rel="stylesheet" href="/css/custom.css">