config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  default_url_options host: "https://dogseekers.herokuapp.com"

  root to: 'homepages#index'

  get "dogs/adoption", as: "adoption_info"
  get "dogs/home", as: "dog_home_info"
  get "dogs/training", as: "training_info"
  get "dogs/problems", as: "problems_info"
  get "dogs/grooming", as: "grooming_info"
  get "dogs/videos", as: "videos"
  get "dogs/involvement", as: "get_involved"
  resources :dogs, only: [:index, :show]

  get "searchs/index"

  namespace :admin do
    resources :dogs, only: [:edit, :create, :update, :new]
  end

  namespace :admin do
    resources :admins, only: [:index, :show]
  end

  resources :breeds, only: [:index, :show]

  devise_scope :admin do
    get "admins/sign_out" => "devise/sessions#destroy"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validate :sanitize_email

  def filters
    bad_filter = LanguageFilter::Filter.new matchlist: :profanity
    sex_filter = LanguageFilter::Filter.new matchlist: :sex
  end

  def sanitize_email
    errors.add(:email, ": This kind of language is inappropriate.") if filters.match?(email)
  end

  has_many :dogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # include search filter in app record for global access
  include SearchFilter
end

app/models/breed.rb
class Breed < ApplicationRecord
end

app/models/dog.rb
require 'gravtastic'
class Dog < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include Gravtastic

  validate :sanitize_dog_name
  validate :sanitize_breed
  validate :sanitize_birth_date
  validate :sanitize_color
  validate :sanitize_photo

  def filters
    bad_filter = LanguageFilter::Filter.new matchlist: :profanity
    sex_filter = LanguageFilter::Filter.new matchlist: :sex
  end
  
  def sanitize_dog_name
    errors.add(:name, ": This kind of language is inappropriate.") if filters.match?(name)
  end

  def sanitize_breed
    errors.add(:breed, ": This kind of language is inappropriate.") if filters.match?(breed)
  end

  def sanitize_color
    errors.add(:color, ": This kind of language is inappropriate.") if filters.match?(color)
  end

  def sanitize_birth_date
    errors.add(:birth_date, ": This kind of language is inappropriate.") if filters.match?(birth_date)
  end

  def sanitize_photo
    errors.add(:photo, ": This kind of language is inappropriate.") if filters.match?(photo)
  end

  gravtastic :secure => true,
             :filetype => :jpg,
             :size => 250

  scope :location, -> (location) { where location: location }
  scope :breed, -> (breed) { where breed: breed }
  scope :title_age, -> (title_age) { where title_age: title_age }
  scope :gender, -> (gender) { where gender: gender }

  validates :name, presence: true
  validates :age, presence: true
  validates :title_age, presence: true
  validates :breed, presence: true
  validates :gender, presence: true
  validates :adoptable, presence: true
  validates :size, presence: true

  belongs_to :admin
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :admins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController

  def index
    @breeds = Breed.all
  end

  def show
    @breed = Breed.find(params[:id])
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
    @posted_by = Admin.find_by(id: @dog.admin_id)
  end

  def adoption
  end

  def home
  end

  def training
  end

  def problems
  end

  def grooming
  end

  def videos
  end

end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  protect_from_forgery with: :exception, prepend: true

  def index
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  
  def index
    @dogs = Dog.search_filter(params.slice(:location, :breed, :title_age, :gender))
  end

end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/dogs_helper.rb
module Admin::DogsHelper
  def is_admins_dog?
    current_admin.id == @dog.admin_id
  end
end

app/helpers/admin/profiles_helper.rb
module Admin::ProfilesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/admin/admins/index.html.erb
<h1 class="admins-dog-index">Showing all dogs for <%= current_admin.email %></h1>
<% if @admins_dogs.any? %>
  <div class="doge-info">
    <div class="container">
      <div class="list-inline">
        <% @admins_dogs.each do |d| %>
          <li class="dog-col-info">
            <h2 class="dog-name"><%= link_to d.name, admin_admin_path(d) %></h2>
            <div class="dog-photo">
              <%= image_tag d.photo, height: "300", width: "350" %>
            </div>
            <h4 class="breed-name"><%= d.name %> is a <%= d.breed %></h4>
            <% if d.gender.titleize == "Female" %>
              <h4 class="dog-age">
                She is <%= d.age %> years old and is a <%= d.size %> sized dog.
              </h4>
            <% else %>
              <h4 class="dog-age">
                He is <%= d.age %> years old and is a <%= d.size %> sized dog.
              </h4>
            <% end %>
          </li>
        <% end %>
      </div>
    </div>
  </div>
  <div class="break-at-bottom-of-dogs">
  </div>
<% else %>
  <div id="no-dogs-yet">
    <h2 class="no-dogs">
      <%= current_admin.email %> hasn't posted any dogs yet. 
      <br/>
      Follow this <%= link_to "link", new_admin_dog_path %> to post a dog for adoption.
    </h2>
  </div>
<% end %>

app/views/admin/admins/show.html.erb
<h1 class="show-admin-dogs">Showing All Dogs for <%= current_admin.email %></h1>

<div id="dog-info-show-page">
  <h2 class="dog-name-show">Meet <%= @admin_dog.name %></h2>

  <div class="doge-info">
    <div class="dog-photo">
      <%= image_tag @admin_dog.photo, height: 300, width: 400 %>
    </div>
    <h4 class="breed-name"><%= @admin_dog.name %> is a <%= @admin_dog.breed %></h4>
    <div class="dog-info-with-gender">
      <% if @admin_dog.gender.titleize == "Female" %>
        <h4 class="dog-age">Title Age: <%= @admin_dog.title_age.titleize %><br><br> Age: <%= @admin_dog.age %></h4>
        <h4 class="dog-size-color">Dog Size: <%= @admin_dog.size.titleize %><br><br> Color: <%= @admin_dog.color.titleize %></h4>
        <h4 class="dog-birth">Birth Date: <%= @admin_dog.birth_date %></h4>
        <h4 class="dog-location">Location: <%= @admin_dog.location %></h4>
      <% else %>
        <h4 class="dog-age">Title Age: <%= @admin_dog.title_age.titleize %><br><br> Age: <%= @admin_dog.age %></h4>
        <h4 class="dog-size-color">Size: <%= @admin_dog.size.titleize %><br><br> Color: <%= @admin_dog.color.titleize %></h4>
        <h4 class="dog-birth">Birth Date: <%= @admin_dog.birth_date %></h4>
        <h4 class="dog-location">Location: <%= @admin_dog.location %></h4>
      <% end %>
    </div>
    <% if @admin_dog.adoptable == true %>
      <h4 class="adoption-available">Available for adoption<h4>
    <% else %>
      <h4 class="adoption-unavailable">Not available for adoption<h4>
    <% end %>
    <center>
      <h5 class="edit-link"><%= link_to "Edit", [:edit, :admin, @admin_dog], class: "edit-dog-link"  %> | </h5>
      <h5 class="back-link"><%= link_to "Back", admin_admins_path, class: "back-to-dogs-link" %></h5>
    </center>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dog Seekers</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="/vendor/magnific-popup/magnific-popup.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="/css/creative.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="/css/custom.css?v=1.0">
    <link rel="stylesheet" href="/css/more-info-pages.css?v=1.0">
    <link rel="stylesheet" href="/css/dog-search-form.css?v=1.0">
    <link rel="stylesheet" href="/css/new-dog-form.css?v=1.0">
    <link rel="stylesheet" href="/css/signin-signup.css?v=1.0">
    <link rel="stylesheet" href="/css/new-dog-form.css?v=1.0">
    <link rel="stylesheet" href="/css/breeds.css?v=1.0">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "jquery-3.1.1.min.js" %>
    <%= javascript_include_tag 'custom' %>

  </head>

  <body id="page-top">
    <%= render "shared/header" %>
    <%= render "shared/main" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
      </button>
      <% if admin_signed_in? %>
        <%= link_to "Sign Out", destroy_admin_session_path, method: :delete, class: "navbar-brand page-scroll" %>
      <% else %>
        <%= link_to "Sign Up", new_admin_registration_path, class: "navbar-brand page-scroll" %>
        <%= link_to "Sign In", new_admin_session_path, class: "navbar-brand page-scroll" %>
      <% end %>
        <%= link_to "Home", root_path, class: "navbar-brand page-scroll" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Find A Dog To Adopt", searchs_index_path, class: "page-scroll" %>
          <ul class="dog-search">
            <div class="search-for-dogs-form">
              <%= form_tag searchs_index_path, method: "get", class: "search-dogs" do %>
                <div id="form-searching-for-dogs">
                  <div class="location">
                    <% label_tag :location, class: "location-label" %>
                    <%= number_field_tag :location, params[:location], max: 0..5, placeholder: "Zip Code", class: "zip-code-area", required: true %>
                  </div>

                  <div class="dog-breed">
                    <% label_tag :breed, class: "breed-label" %>
                    <%= text_field_tag :breed, params[:breed], placeholder: "Breed", class: "breed-text-field" %>
                  </div>

                  <div class="search-dog-age">
                    <p class="age-name">Choose an Age:</p>
                    <%= radio_button_tag :title_age, "baby", id: "age-baby" %>
                    <%= label_tag :title_age_baby, "Baby: 0-2 years", class: "age-baby" %>
                    <br/>
                    <%= radio_button_tag :title_age, "young", id: "age-young" %>
                    <%= label_tag :title_age_young, "Young: 3-5 years", class: "age-young" %>
                    <br/>
                    <%= radio_button_tag :title_age, "adult", id: "age-adult" %>
                    <%= label_tag :title_age_adult, "Adult: 6-8 years", class: "age-adult" %>
                  </div>

                  <div class="dog-gender">
                    <% label_tag :gender, class: "gender-label" %>
                    <%= text_field_tag :gender, params[:gender], placeholder: "Dog Gender", class: "gender-text-field" %>
                  </div>

                  <div class="submit-button-for-search">
                    <%= submit_tag "Search for Dogs", name: nil, class: "dog-search-submit-button" %>
                  </div>
                </div>
              <% end %>
            </div>
          </ul>
        </li>
        <% if admin_signed_in? %>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <li>
            <%= link_to "All Dogs", admin_admins_path, class: "page-scroll" %>
          </li>
          <li>
            <%= link_to "Post a Dog for Adoption", new_admin_dog_path, class: "page-scroll" %>
          </li>
        <% else %>
          <li>
            <a class="page-scroll" href="#about">About Dog Adoption</a>
            <ul class="about-dog-adoption">
              <li><%= link_to "More About Dog Adoption", adoption_info_path, class: "dog-adopt-info" %></li>
            </ul>
          </li>
          <li>
            <a class="page-scroll" href="#services">Dog Care</a>
            <ul class="dog-care">
              <li><%= link_to "Dog Breeds", breeds_path, class: "dog-care-info" %></li>
              <li><%= link_to "Home Care", dog_home_info_path, class: "dog-care-info" %></li>
              <li><%= link_to "Dog Training", training_info_path, class: "dog-care-info" %></li>
              <li><%= link_to "Dog Problems", problems_info_path, class: "dog-care-info" %></li>
              <li><%= link_to "Dog Grooming", grooming_info_path, class: "dog-care-info" %></li>
              <li><%= link_to "Dog Care Videos", videos_path, class: "dog-care-info" %></li>
            </ul>
          </li>
          <li>
            <a class="page-scroll" href="#portfolio">Some of Our Pets</a>
            <ul class="our-pets">
              <li><%= link_to "See All Dogs", dogs_path, class: "all-our-pets" %></li>
            </ul>
          </li>
          <li>
            <a class="page-scroll" href="#contact">Helping Dogs</a>
            <ul class="help-dogs">
              <li><%= link_to "Get Involved", get_involved_path, class: "dog-involvement" %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
      <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/shared/_main.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="col-md-8">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert" &#215;></a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%>
        </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <%= yield :sidebar %>
    </div>
  </div>
</div>