config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  default_url_options host: "https://dogseekers.herokuapp.com"

  root to: 'homepages#index'

  get "dogs/adoption", as: "adoption_info"
  get "dogs/home", as: "dog_home_info"
  get "dogs/training", as: "training_info"
  get "dogs/problems", as: "problems_info"
  get "dogs/grooming", as: "grooming_info"
  get "dogs/videos", as: "videos"
  get "dogs/involvement", as: "get_involved"
  resources :dogs, only: [:index, :show]

  get "searchs/index"

  namespace :admin do
    resources :dogs, only: [:edit, :create, :update, :new]
  end

  namespace :admin do
    resources :admins, only: [:index, :show]
  end

  resources :breeds, only: [:index, :show]

  devise_scope :admin do
    get "admins/sign_out" => "devise/sessions#destroy"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validate :sanitize_email

  def filters
    bad_filter = LanguageFilter::Filter.new matchlist: :profanity
    sex_filter = LanguageFilter::Filter.new matchlist: :sex
  end

  def sanitize_email
    errors.add(:email, ": This kind of language is inappropriate.") if filters.match?(email)
  end

  has_many :dogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # include search filter in app record for global access
  include SearchFilter
end

app/models/breed.rb
class Breed < ApplicationRecord
end

app/models/concerns/search_filter.rb
module SearchFilter
  extend ActiveSupport::Concern

  module ClassMethods
    def search_filter(filter_params)
      results = self.where(nil)
      filter_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/dog.rb
require 'gravtastic'
class Dog < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include Gravtastic

  validate :sanitize_dog_name
  validate :sanitize_breed
  validate :sanitize_birth_date
  validate :sanitize_color
  validate :sanitize_photo

  def filters
    bad_filter = LanguageFilter::Filter.new matchlist: :profanity
    sex_filter = LanguageFilter::Filter.new matchlist: :sex
  end
  
  def sanitize_dog_name
    errors.add(:name, ": This kind of language is inappropriate.") if filters.match?(name)
  end

  def sanitize_breed
    errors.add(:breed, ": This kind of language is inappropriate.") if filters.match?(breed)
  end

  def sanitize_color
    errors.add(:color, ": This kind of language is inappropriate.") if filters.match?(color)
  end

  def sanitize_birth_date
    errors.add(:birth_date, ": This kind of language is inappropriate.") if filters.match?(birth_date)
  end

  def sanitize_photo
    errors.add(:photo, ": This kind of language is inappropriate.") if filters.match?(photo)
  end

  gravtastic :secure => true,
             :filetype => :jpg,
             :size => 250

  scope :location, -> (location) { where location: location }
  scope :breed, -> (breed) { where breed: breed }
  scope :title_age, -> (title_age) { where title_age: title_age }
  scope :gender, -> (gender) { where gender: gender }

  validates :name, presence: true
  validates :age, presence: true
  validates :title_age, presence: true
  validates :breed, presence: true
  validates :gender, presence: true
  validates :adoptable, presence: true
  validates :size, presence: true

  belongs_to :admin
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :admins
end

app/controllers/admin/dogs_controller.rb
class Admin::DogsController < ApplicationController
  before_action :set_dog, only: [:edit, :update]
  before_action :authenticate_admin!

  def new
    @dog = Dog.new
  end

  def create 
    @dog = Dog.new(dog_params)
    @dog.admin_id = current_admin.id
    if @dog.save
      AdminMailer.create_dog_email(current_admin).deliver_now
      flash[:success] = "Dog added successfully."
      redirect_to admin_admins_path
    else
      flash.now[:danger] = "Dog not added."
      render :new
    end
  end

  def edit
    if @dog.admin_id != current_admin.id
      flash[:danger] = "You can only edit the dog you posted"
      redirect_to admin_admins_path
    end
  end

  def update
    if @dog.admin_id != current_admin.id
      flash[:danger] = "You can only edit the dog you posted"
      redirect_to admin_admins_path
    else
      if @dog.update(dog_params)
        AdminMailer.update_dog_email(current_admin).deliver_now
        flash[:success] = "Dog successfully updated"
        redirect_to admin_admin_path(@dog)
      else
        flash.now[:danger] = "Dog unsuccessfully updated"
        render :edit
      end
    end
  end

  private

    def dog_params
      params.require(:dog)
        .permit(:name, :age, :breed, :gender, :adoptable,
                :color, :size, :photo, :location, :title_age, :birth_date)
    end

    def set_dog
      @dog = Dog.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController

  def index
    @breeds = Breed.all
  end

  def show
    @breed = Breed.find(params[:id])
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
    @posted_by = Admin.find_by(id: @dog.admin_id)
  end

  def adoption
  end

  def home
  end

  def training
  end

  def problems
  end

  def grooming
  end

  def videos
  end

end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  protect_from_forgery with: :exception, prepend: true

  def index
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  
  def index
    @dogs = Dog.search_filter(params.slice(:location, :breed, :title_age, :gender))
  end

end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/dogs_helper.rb
module Admin::DogsHelper
  def is_admins_dog?
    current_admin.id == @dog.admin_id
  end
end

app/helpers/admin/profiles_helper.rb
module Admin::ProfilesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/homepages/index.html.erb
<header>
  <div class="header-content">
    <div class="header-content-inner">
      <h1 id="homeHeading">Welcome To Dog Seekers</h1>
      <hr>
      <p>
        This site is to help search for the perfect dog for your perfect life.
      </p>
      <a href="#about" class="btn btn-primary btn-xl page-scroll">About Dog Seeker</a>
    </div>
  </div>
</header>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
          <h2 class="section-heading">We've got the dog just for you!</h2>
          <hr class="light">
          <p class="text-faded">
            Dog Seeker is the number one dog finding site in the country.

            We're happy to help you find a great addition to your wonderful family!
          </p>
          <a href="#services" class="page-scroll btn btn-default btn-xl sr-button">Get Started!</a>
      </div>
    </div>
  </div>
</section>

<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Dogs, Dogs and More Dogs!</h2>
        <hr class="primary">
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <img src="img/doge4.jpg" class="image-doge-one" height="100" width="160">
          <h3>We have Puppies</h3>
          <p class="text-muted">We have a great deal of puppies for you to choose from.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <img src="img/doge2.jpg" class="image-doge-one" height="100" width="160">
          <h3>We have Young Dogs</h3>
          <p class="text-muted">We have a great deal of young healthy dogs for you to choose from.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <img src="img/doge3.jpg" class="image-doge-one" height="100" width="160">
          <h3>We have Adult Dogs</h3>
          <p class="text-muted">We have a great deal of healthy adult dogs for you to choose from.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <img src="img/doge1.jpg" class="image-doge-one" height="100" width="200">
          <h3>We have a variety of breeds as well!</h3>
          <p class="text-muted">We have a great deal of breeds for you to choose from as well.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="no-padding" id="portfolio">
  <div class="container-fluid">
    <div class="row no-gutter popup-gallery">
      <div class="col-lg-4 col-sm-6">
        <a href="img/portfolio/fullsize/doge6.jpg" class="portfolio-box">
        <img src="img/portfolio/thumbnails/doge6.jpg" class="img-responsive" alt="">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category text-faded">
                Some of Our Pets
              </div>
              <div class="project-name">
                Check out our available dogs to adopt 
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-4 col-sm-6">
        <a href="img/portfolio/fullsize/doge7.jpg" class="portfolio-box">
          <img src="img/portfolio/thumbnails/doge7.jpg" class="img-responsive" alt="">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
                <div class="project-category text-faded">
                  Some of Our Pets
                </div>
                <div class="project-name">
                  Check out our available dogs to adopt 
                </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-4 col-sm-6">
        <a href="img/portfolio/fullsize/doge8.jpg" class="portfolio-box">
          <img src="img/portfolio/thumbnails/doge8.jpg" class="img-responsive" alt="">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category text-faded">
                Some of Our Pets
              </div>
              <div class="project-name">
                Check out our available dogs to adopt 
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-4 col-sm-6">
        <a href="img/portfolio/fullsize/doge9.jpg" class="portfolio-box">
          <img src="img/portfolio/thumbnails/doge9.jpg" class="img-responsive" alt="">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category text-faded">
                Some of Our Pets
              </div>
              <div class="project-name">
                Check out our available dogs to adopt 
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-4 col-sm-6">
        <a href="img/portfolio/fullsize/doge10.jpg" class="portfolio-box">
          <img src="img/portfolio/thumbnails/doge10.jpg" class="img-responsive" alt="">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category text-faded">
                Some of Our Pets
              </div>
              <div class="project-name">
                Check out our available dogs to adopt 
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-4 col-sm-6">
        <a href="img/portfolio/fullsize/doge5.jpg" class="portfolio-box">
          <img src="img/portfolio/thumbnails/doge5.jpg" class="img-responsive" alt="">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category text-faded">
                Some of Our Pets
              </div>
              <div class="project-name">
                Check out our available dogs to adopt 
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>
</section>

<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading">Get In Touch!</h2>
        <hr class="primary">
        <p>
          Please feel free to reach out with any questions about our dogs, services, or dog care information.
        </p>
      </div>
      <div class="col-lg-4 col-lg-offset-2 text-center">
        <i class="fa fa-phone fa-3x sr-contact"></i>
        <p>1-800-Dog-Seekers</p>
      </div>
      <div class="col-lg-4 text-center">
        <i class="fa fa-envelope-o fa-3x sr-contact"></i>
        <p><a href="mailto:dog.seekers@gmail.com">dog.seekers@gmail.com</a></p>
      </div>
    </div>
  </div>
</section>

<center>
  <footer role="contentinfo">
    <p><small>
      <a class="copyright" href="https://kylestengline.com/" target="_blank">
        Copyright &copy; 2018 Kyle Stengline</small>
      </a>
    </p>
  </footer>
</center>
<!-- jQuery -->
<script src="/vendor/jquery/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/vendor/bootstrap/js/bootstrap.min.js"></script>

<!-- Plugin JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
<script src="/vendor/scrollreveal/scrollreveal.min.js"></script>
<script src="/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

<!-- Theme JavaScript -->
<script src="/js/creative.min.js"></script>

app/views/searchs/index.html.erb
<div class="doge-info">
  <div class="list-inline">
    <% @dogs.each do |d| %>
      <li class="dog-col-info">
        <h2 class="dog-name">Meet <%= link_to d.name, dog_path(d.id) %></h2>
        <div class="dog-photo">
          <%= image_tag d.photo, height: "300", width: "350" %>
        </div>
        <h4 class="breed-name"><%= d.name %> is a <%= d.breed %></h4>
        <% if d.gender.titleize == "Female" %>
          <h4 class="dog-age">She is <%= d.age %> years old.</h4>
        <% else %>
          <h4 class="dog-age">He is <%= d.age %> years old.</h4>
        <% end %>
      </li>
    <% end %>
  </div>
  <div class="break-at-bottom-of-dogs">
  </div>
  <% unless @dogs.present? %>
    <div class="no-doges-match">
      <h3 class="search-returns-none">
        No Dogs match your search criteria. Please try your search again.
      </h3>
    </div>
  <% end %>
</div>